CREATE TABLE SECUR_AUTH.USER_INFO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ABOUT_ME VARCHAR(5000)
);

CREATE TABLE SECUR_AUTH.ROLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE SECUR_AUTH.USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    USER_INFO_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,

    FOREIGN KEY(USER_INFO_ID)
    REFERENCES USER_INFO(ID)
    ON DELETE CASCADE,

    FOREIGN KEY(ROLE_ID)
    REFERENCES ROLE(ID)
);