CREATE TABLE SECUR_AUTH.USER_ROLE
(
    USER_ID BIGINT NOT NULL UNIQUE,
    ROLE_ID BIGINT NOT NULL UNIQUE,
    CONSTRAINT pk_userRole PRIMARY KEY (USER_ID, ROLE_ID),

    CONSTRAINT fk_user FOREIGN KEY(USER_ID)
        REFERENCES USER(ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_role FOREIGN KEY(ROLE_ID)
        REFERENCES ROLE(ID)
        ON DELETE CASCADE
);